src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import handler404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]

handler404 = "main.views.handler404"  # NOQA

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/urls.py
from django.urls import path
from groups.views import GroupsUpdateView, GroupsDeleteView, GroupsGetView, GroupsCreateView

app_name = "groups"  # NOQA

urlpatterns = [
    path("", GroupsGetView.as_view(), name="get_groups"),
    path("create/", GroupsCreateView.as_view(), name="create_groups"),
    path("update/<int:pk>/", GroupsUpdateView.as_view(), name="update_groups"),
    path("delete/<int:pk>/", GroupsDeleteView.as_view(), name="delete_groups"),
]

src/main/urls.py
from django.urls import path

from main.views import (
    IndexView,
    UserRegistrationView,
    UserLoginView,
    UserLogoutView,
    UserActivateView,
    send_test_email,
    UserProfileUpdateView,
)


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("login", UserLoginView.as_view(), name="login"),
    path("logout", UserLogoutView.as_view(), name="logout"),
    path("activate/<str:uuid64>/<str:token>/", UserActivateView.as_view(), name="activate_user"),
    path("send_test_email", send_test_email, name="send_test_email"),
    path("profile/<int:pk>/", UserProfileUpdateView.as_view(), name="userprofile_update"),
]

src/students/urls.py
from django.urls import path
from students.views import StudentUpdateView, StudentDeleteView, StudentGetView, StudentCreateView

app_name = "students"  # NOQA

urlpatterns = [
    path("", StudentGetView.as_view(), name="get_students"),
    path("create/", StudentCreateView.as_view(), name="create_students"),
    path("update/<int:pk>/", StudentUpdateView.as_view(), name="update_students"),
    path("delete/<int:pk>/", StudentDeleteView.as_view(), name="delete_students"),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import (
    TeachersUpdateView,
    TeachersDeleteView,
    TeachersGetView,
    TeachersCreateView,
    TeacherGroupsView,
)

app_name = "teachers"  # NOQA

urlpatterns = [
    path("", TeachersGetView.as_view(), name="get_teachers"),
    path("create/", TeachersCreateView.as_view(), name="create_teachers"),
    path("update/<int:pk>/", TeachersUpdateView.as_view(), name="update_teachers"),
    path("delete/<int:pk>/", TeachersDeleteView.as_view(), name="delete_teachers"),
    path("groups/<int:pk>/", TeacherGroupsView.as_view(), name="groups_of_teacher"),
]

src/templates/11.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<img src="{% static 'img/404.jpg' %}" alt="404 Image">
</body>
</html>

src/templates/create_user.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em; margin: auto">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-info" value="Register">Submit</button>
        </form>
    </div>

{% endblock %}
</body>
</html>

src/templates/groups_delete.html
{% extends 'index.html' %}

{% block content %}
    <div>
        Are you sure you want to delete {{ groups.group_leader }}'s group? <br>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-success" name="submit_yes" value="Submit">Yes</button>
            <a href="{% url 'groups:get_groups' %}" class="btn btn-danger">No</a>
        </form>
    </div>
{% endblock %}

src/templates/groups_list.html
{% extends "index.html" %}

{% block content %}

<div class="input-group mb-3">
  <form method="GET" action="{% url 'groups:get_groups' %}">
    <input type="text" class="form-control" placeholder="any field" aria-label="Recipient's username" aria-describedby="button-addon2" name="search">
    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Search</button>
  </form>

      <a type="button" class="btn btn-success" href="{% url 'groups:create_groups' %}">Add new group</a>

</div>


<div>
    <table class="table table-dark table-sm">
        <thead>
            <tr>
                <th scope="col">Group ID</th>
                <th scope="col">Group Leader</th>
                <th scope="col">Start Date</th>
                <th scope="col">End Date</th>
                <th scope="col">Speciality</th>
                <th scope="col">Average grade</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>

            {% for group in groups %}
            <tr>
                <td>{{ group.group_id }}</td>
                <td>{{ group.group_leader }}</td>
                <td>{{ group.start_date }}</td>
                <td>{{ group.end_date }}</td>
                <td>{{ group.speciality }}</td>
                <td>{{ group.average_grade }}</td>
                <td>
                    <a type="button" class="btn btn-warning" href="{% url 'groups:update_groups' group.pk %}">Edit</a>
                    <a type="button" class="btn btn-danger" href="{% url 'groups:delete_groups' group.pk %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

src/templates/index.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100" data-bs-theme="auto">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>Cover Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/cover/">


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">


<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-bg-dark">
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">SP LMS</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="{% url 'index' %}">Home</a>
        <a class="nav-link fw-bold py-1 px-0" href="{% url 'students:get_students' %}">&nbsp Students &nbsp</a>
        <a class="nav-link fw-bold py-1 px-0" href="{% url 'teachers:get_teachers' %}">&nbsp Teachers &nbsp</a>
        <a class="nav-link fw-bold py-1 px-0" href="{% url 'groups:get_groups' %}">&nbsp Groups &nbsp</a>
          <div class="dropdown">
        {% if not user.is_authenticated %}
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Sign In
        </button>
            {% else %}
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Profile
        </button>
            {% endif %}
        <ul class="dropdown-menu">


          <li>
            <hr class="dropdown-divider" >
          </li>
          {% if not user.is_authenticated %}
          <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
          <li><a class="dropdown-item" href="{% url 'social:begin' 'google-oauth2' %}">Login via Google</a></li>
          <li><a class="dropdown-item" href="{% url 'social:begin' 'github' %}">Login via GitHub</a></li>
          <li><a class="dropdown-item" href="{% url 'social:begin' 'gitlab' %}">Login via GitLab</a></li>
          <li><a class="dropdown-item" href="{% url 'social:begin' 'reddit' %}">Login via Reddit</a></li>
          <li><a class="dropdown-item" href="{% url 'social:begin' 'facebook' %}">Login via Facebook (only localhost!)</a></li>

          <li><a class="dropdown-item" href="{% url 'register' %}">Registration</a></li>
          {% endif %}
          <li>
            <hr class="dropdown-divider" >
          </li>
          {% if user.is_authenticated %}
          <li><a class="dropdown-item" href="{% url 'logout' %}">Sign out</a></li>
          {% endif %}
        </ul>
          </div>
      </nav>
    </div>


  </header>

  <main class="px-3">
      {% block content %}
      <h1>{{ site_name }}</h1>
      <p class="lead">{{ description }}</p>
      <p class="lead">{{ description }}</p
      <p class="lead">
          <img src="{% static 'img/LMS.jpg' %}" alt="LMS Image">
      </p>
        <a href="#" class="btn btn-lg btn-light fw-bold border-white bg-white">Learn more</a>
      </p>
      {% endblock %}
  </main>

  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
  </footer>
</div>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    </body>
</html>

src/templates/person_create.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em; margin: auto">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-info" value="Submit">Submit</button>
        </form>
    </div>

{% endblock %}

src/templates/person_update.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em; margin: auto">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-info" value="Submit">Save</button>
        </form>
    </div>

{% endblock %}

src/templates/students_delete.html
{% extends 'index.html' %}

{% block content %}
    <div>
        Are you sure you want to delete {{ student.first_name }} {{ student.last_name }}? <br>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-success" name="submit_yes" value="Submit">Yes</button>
            <a href="{% url 'students:get_students' %}" class="btn btn-danger">No</a>
        </form>
    </div>
{% endblock %}

src/templates/teacher_search_result.html
{% extends "index.html" %}

{% block content %}



    <div>

        <table class="table table-dark table-sm">
            <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">First Name</th>
                  <th scope="col">Last Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Phone number</th>
                  <th scope="col">Birth date</th>
                  <th scope="col">Start date</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
              <a type="button" class="btn btn-success"
                            href="{% url 'teachers:create_teacher' %}">Add new teacher</a>

              {% for teacher in teachers%}
                    <tr>
                      <th scope="row">{{ teacher.pk }}</th>
                      <td>{{ teacher.first_name }}</td>
                      <td>{{ teacher.last_name }}</td>
                      <td>{{ teacher.email }}</td>
                      <td>{{ teacher.phone_number }}</td>
                      <td>{{ teacher.birth_date }}</td>
                      <td>{{ teacher.start_date }}</td>
                      <td><a type="button" class="btn btn-warning"
                            href="{% url 'teachers:update_teacher' teacher.pk %}">Edit</a>
                          <a type="button" class="btn btn-danger"
                            href="{% url 'teachers:delete_teacher' teacher.pk %}">Delete</a>
                      </td>
                    </tr>
              {% endfor %}

     </div>

{% endblock content %}

src/templates/teachers_delete.html
{% extends 'index.html' %}

{% block content %}
    <div>
        Are you sure you want to delete {{ teachers.first_name }} {{ teachers.last_name }}? <br>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-success" name="submit_yes" value="Submit">Yes</button>
            <a href="{% url 'teachers:get_teachers' %}" class="btn btn-danger">No</a>
        </form>
    </div>
{% endblock %}

src/templates/teachers_groups.html
{% extends "index.html" %}

{% block content %}

<div>
    <table class="table table-dark table-sm">
        <thead>
            <tr>
                <th scope="col">Group ID</th>
                <th scope="col">Group Leader</th>
                <th scope="col">Start Date</th>
                <th scope="col">End Date</th>
                <th scope="col">Speciality</th>
                <th scope="col">Average Grade</th>
            </tr>
        </thead>
        <tbody>
            <h1> Groups of {{ teacher.first_name }} {{ teacher.last_name }}</h1>

            {% for group in teacher_groups %}
            <tr>
                <td>{{ group.group_id }}</td>
                <td>{{ group.group_leader }}</td>
                <td>{{ group.start_date }}</td>
                <td>{{ group.end_date }}</td>
                <td>{{ group.speciality }}</td>
                <td>{{ group.average_grade }}</td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}