src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import handler404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]

handler404 = "main.views.handler404"  # NOQA

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path

from main.views import (
    IndexView,
    UserRegistrationView,
    UserLoginView,
    UserLogoutView,
    UserActivateView,
    send_test_email,
    UserProfileUpdateView,
)


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("login", UserLoginView.as_view(), name="login"),
    path("logout", UserLogoutView.as_view(), name="logout"),
    path("activate/<str:uuid64>/<str:token>/", UserActivateView.as_view(), name="activate_user"),
    path("send_test_email", send_test_email, name="send_test_email"),
    path("profile/<int:pk>/", UserProfileUpdateView.as_view(), name="userprofile_update"),
]

src/students/urls.py
from django.urls import path
from students.views import StudentUpdateView, StudentDeleteView, StudentGetView, StudentCreateView

app_name = "students"  # NOQA

urlpatterns = [
    path("", StudentGetView.as_view(), name="get_students"),
    path("create/", StudentCreateView.as_view(), name="create_students"),
    path("update/<int:pk>/", StudentUpdateView.as_view(), name="update_students"),
    path("delete/<int:pk>/", StudentDeleteView.as_view(), name="delete_students"),
]

src/students/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from faker import Faker
import random

from main.models import Person
from students.utils.validators import validate_file_size
from groups.models import Groups


# Create your models here.
# ORM


class Student(Person):
    grade = models.PositiveSmallIntegerField(null=True, blank=True)
    group = models.ForeignKey(Groups, on_delete=models.CASCADE, default=str(random.randint(1, 20)))
    photo = models.ImageField(upload_to="students/", null=True, blank=True)
    cv = models.FileField(
        upload_to="students_cv/",
        null=True,
        blank=True,
        validators=[FileExtensionValidator(allowed_extensions=("pdf", "doc", "docx")), validate_file_size],
    )

    class Meta:
        verbose_name = "One Student"
        verbose_name_plural = "All Students"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birth_date=faker.date_of_birth(minimum_age=18, maximum_age=60),
                group_id=str(random.randint(1, 20)),
            )

src/students/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from students.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ["first_name", "last_name", "email", "group", "grade"]

    @staticmethod
    def normalize_text(text):
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]
        if "yandex" in email.lower():
            raise ValidationError("Yandex is not a valid email address!")
        return email

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]
        if first_name == last_name:
            raise ValidationError("First and last names cannot be the same")

src/students/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView

from students.forms import StudentForm
from students.models import Student


class StudentCreateView(LoginRequiredMixin, CreateView):
    template_name = "person_create.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:get_students")


class StudentUpdateView(LoginRequiredMixin, UpdateView):
    model = Student
    template_name = "person_update.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:get_students")


class StudentGetView(LoginRequiredMixin, ListView):
    model = Student
    template_name = "students_list.html"
    context_object_name = "students"

    def __init__(self):
        print("base2:", self.__class__.__base__)


class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    template_name = "students_delete.html"
    success_url = reverse_lazy("students:get_students")

src/templates/students/student_list.html
{% extends "index.html" %}

{% block content %}

<div class="input-group mb-3">
  <form method="GET" action="{% url 'students:get_students' %}">
    <input type="text" class="form-control" placeholder="Students's name" aria-label="Recipient's username" aria-describedby="button-addon2" name="search">
    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Search</button>
  </form>

      <a type="button" class="btn btn-success" href="{% url 'students:create_students' %}">Add new student</a>

</div>


<div>
    <table class="table table-dark table-sm">
        <thead>
            <tr>
                <th scope="col">Photo</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
                <th scope="col">Birth date</th>
                <th scope="col">Group</th>
                <th scope="col">Grade</th>
                <th scope="col">Student's CV</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>


            {% for student in students %}
            <tr>
                <td>
                    {% if student.photo %}
                    <img src="{{ student.photo.url }}" alt="{{ student.first_name }} {{ student.last_name }}" style="max-width: 120px; max-height: 120px;">

                    {% else %}
                    <p> no image </p>
                    {% endif %}
                </td>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.birth_date }}</td>
                <td>{{ student.group }}</td>
                <td>{{ student.grade }}</td>
                <td>
                    {% if student.cv %}
                    <a type="button" class="btn btn-warning" href="{{ student.cv.url }}">Download CV</a>
                    {% else %}
                    <p> no cv </p>
                    {% endif %}
                </td>
                <td>
                    <a type="button" class="btn btn-warning" href="{% url 'students:update_students' student.pk %}">Edit</a>
                    <a type="button" class="btn btn-danger" href="{% url 'students:delete_students' student.pk %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}