src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import handler404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]

handler404 = "main.views.handler404"  # NOQA

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path

from main.views import (
    IndexView,
    UserRegistrationView,
    UserLoginView,
    UserLogoutView,
    UserActivateView,
    send_test_email,
    UserProfileUpdateView,
)


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("login", UserLoginView.as_view(), name="login"),
    path("logout", UserLogoutView.as_view(), name="logout"),
    path("activate/<str:uuid64>/<str:token>/", UserActivateView.as_view(), name="activate_user"),
    path("send_test_email", send_test_email, name="send_test_email"),
    path("profile/<int:pk>/", UserProfileUpdateView.as_view(), name="userprofile_update"),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import (
    TeachersUpdateView,
    TeachersDeleteView,
    TeachersGetView,
    TeachersCreateView,
    TeacherGroupsView,
)

app_name = "teachers"  # NOQA

urlpatterns = [
    path("", TeachersGetView.as_view(), name="get_teachers"),
    path("create/", TeachersCreateView.as_view(), name="create_teachers"),
    path("update/<int:pk>/", TeachersUpdateView.as_view(), name="update_teachers"),
    path("delete/<int:pk>/", TeachersDeleteView.as_view(), name="delete_teachers"),
    path("groups/<int:pk>/", TeacherGroupsView.as_view(), name="groups_of_teacher"),
]

src/teachers/models.py
from django.db import models
from faker import Faker
from groups.models import Groups
from main.models import Person


# Create your models here.
# ORM


class Teachers(Person):
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    groups = models.ManyToManyField(Groups, related_name="teachers")
    photo = models.ImageField(upload_to="stuff/", null=True, blank=True)

    @classmethod  # NOQA
    def generate_instances(cls, count):
        faker = Faker()
        for _ in range(count):
            teacher = cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                phone_number=faker.phone_number(),
                birth_date=faker.date_of_birth(minimum_age=30, maximum_age=78),
                start_date=faker.date_this_century(),
            )
            iterations = 3
            while iterations != 0:
                random_group = Groups.objects.order_by("?").first()  # NOQA
                teacher.groups.add(random_group)
                iterations -= 1

src/teachers/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from teachers.models import Teachers


class TeacherForm(ModelForm):
    class Meta:
        model = Teachers
        fields = ["first_name", "last_name", "email", "groups"]

    @staticmethod
    def normalize_text(text):
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]
        if "yandex" in email.lower():
            raise ValidationError("Yandex is not a valid email address!")
        return email

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]
        if first_name == last_name:
            raise ValidationError("First and last names cannot be the same")

src/teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView

from teachers.forms import TeacherForm
from teachers.models import Teachers


class TeachersCreateView(LoginRequiredMixin, CreateView):
    template_name = "person_create.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teachers")


class TeachersUpdateView(LoginRequiredMixin, UpdateView):
    model = Teachers
    template_name = "person_update.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teachers")


class TeachersGetView(LoginRequiredMixin, ListView):
    model = Teachers
    template_name = "teachers_list.html"
    context_object_name = "teachers"


class TeachersDeleteView(LoginRequiredMixin, DeleteView):
    model = Teachers
    template_name = "teachers_list.html"
    success_url = reverse_lazy("teachers:get_teachers")


class TeacherGroupsView(LoginRequiredMixin, DetailView):
    model = Teachers
    template_name = "teachers_groups.html"
    context_object_name = "teacher"
    pk_url_kwarg = "pk"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teacher = self.object
        context["teacher_groups"] = teacher.groups.all()
        return context

src/templates/teachers/teachers_list.html
{% extends "index.html" %}

{% block content %}

<div class="input-group mb-3">
  <form method="GET" action="{% url 'teachers:get_teachers' %}">
    <input type="text" class="form-control" placeholder="Teacher's name" aria-label="Recipient's username" aria-describedby="button-addon2" name="search">
    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Search</button>
  </form>
    <a type="button" class="btn btn-success" href="{% url 'teachers:create_teachers' %}">Add new teacher</a>
</div>


<div>
    <table class="table table-dark table-sm">
        <thead>
            <tr>
                <th scope="col">Photo</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone number</th>
                <th scope="col">Birth date</th>
                <th scope="col">Start date</th>
                <th scope="col">Groups</th>
                <th scope="col">Actions</th>

            </tr>
        </thead>
        <tbody>

            {% for teacher in teachers %}
            <tr>
                <tr>
                <td>
                    {% if teacher.photo %}
                    <img src="{{ teacher.photo.url }}" alt="{{ teacher.first_name }} {{ teacher.last_name }}" style="max-width: 120px; max-height: 120px;">

                    {% else %}
                    <p> no image </p>
                    {% endif %}
                </td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.phone_number }}</td>
                <td>{{ teacher.birth_date }}</td>
                <td>{{ teacher.start_date }}</td>
                <td>
                    <a type="button" class="btn btn-secondary" href="{% url 'teachers:groups_of_teacher' teacher.pk %}">Group list</a>
                </td>

                <td>
                    <a type="button" class="btn btn-warning" href="{% url 'teachers:update_teachers' teacher.pk %}">Edit</a>
                    <a type="button" class="btn btn-danger" href="{% url 'teachers:delete_teachers' teacher.pk %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}